POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWZpZXN0LmNvbSIsInJvbGUiOiJhZG1pbmlzdHJhZG9yIiwiaWF0IjoxNzU4NTcxOTA2LCJleHAiOjE3NTg1NzU1MDZ9._JA53JiIKYc8OgQOnOvDxIByA5xm6KucUmB6Sl5xLMU

{
  "name": "Super Admin",
  "email": "admin@mafiest.com",
  "password": "admin123",
  "role": "administrador",
}